name: Increment Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "increment/**"
      - ".github/workflows/increment-tests.yml"
  push:
    branches:
      - main
    paths:
      - "increment/**"
      - ".github/workflows/increment-tests.yml"

jobs:
  test-ios:
    name: Run iOS Tests
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Cache derived data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-${{ hashFiles('increment/**/*.swift', 'increment/**/*.xcodeproj/**', 'increment/**/*.xcworkspace/**') }}
          restore-keys: |
            ${{ runner.os }}-xcode-

      - name: Initialize simulator service
        run: xcrun simctl list > /dev/null

      - name: Download iOS Platform
        run: xcodebuild -downloadPlatform iOS

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Run tests on iOS Simulator
        working-directory: increment/IncrementProject
        run: |
          xcodebuild test \
            -workspace Increment.xcworkspace \
            -scheme Increment \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
            -resultBundlePath TestResults.xcresult \
            -enableCodeCoverage YES \
            | xcpretty --color --report html --output test-results.html

      - name: Upload xcresult bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcresult-bundle
          path: increment/IncrementProject/TestResults.xcresult
          retention-days: 1
