name: Increment Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'increment/**'
      - '.github/workflows/increment-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'increment/**'
      - '.github/workflows/increment-tests.yml'

jobs:
  test-ios:
    name: Run iOS Tests
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Show available SDKs
        run: xcodebuild -showsdks

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Get iPhone 16 simulator ID
        id: sim
        run: |
          SIM_ID=$(xcrun simctl list devices available | grep -A20 "iOS 18.4" | grep "iPhone 16 (" | head -1 | sed 's/.*(\([A-F0-9-]*\)) .*/\1/')
          echo "uuid=$SIM_ID" >> $GITHUB_OUTPUT
          echo "Using simulator: $SIM_ID"

      - name: Run tests on iOS Simulator
        working-directory: increment/IncrementProject
        run: |
          xcodebuild test \
            -workspace Increment.xcworkspace \
            -scheme Increment \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,id=${{steps.sim.outputs.uuid}}" \
            -resultBundlePath TestResults.xcresult \
            -enableCodeCoverage YES \
            | xcpretty --color --report html --output test-results.html

      - name: Publish test results summary
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: increment/IncrementProject/TestResults.xcresult
          show-passed-tests: true
          show-code-coverage: true
        if: success() || failure()

      - name: Upload xcresult bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcresult-bundle
          path: increment/IncrementProject/TestResults.xcresult
          retention-days: 30
