name: Increment Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'increment/**'
      - '.github/workflows/increment-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'increment/**'
      - '.github/workflows/increment-tests.yml'

jobs:
  test-ios:
    name: Run iOS Tests
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available simulators
        run: xcrun simctl list devices available

      - name: Run tests on iOS Simulator
        working-directory: increment/IncrementProject
        run: |
          xcodebuild test \
            -workspace Increment.xcworkspace \
            -scheme IncrementFeature \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -resultBundlePath TestResults.xcresult \
            -enableCodeCoverage YES \
            | xcpretty --color --report html --output test-results.html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: increment/IncrementProject/test-results.html
          retention-days: 30

      - name: Upload xcresult bundle
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcresult-bundle
          path: increment/IncrementProject/TestResults.xcresult
          retention-days: 30

      - name: Check test results
        if: always()
        working-directory: increment/IncrementProject
        run: |
          if [ -d "TestResults.xcresult" ]; then
            xcrun xcresulttool get --format json --path TestResults.xcresult > test-summary.json
            echo "Test results saved to test-summary.json"

            # Check for test failures
            FAILED_TESTS=$(xcrun xcresulttool get --format json --path TestResults.xcresult | jq '.issues.testFailureSummaries | length')
            if [ "$FAILED_TESTS" -gt 0 ]; then
              echo "❌ $FAILED_TESTS test(s) failed"
              exit 1
            else
              echo "✅ All tests passed"
            fi
          fi
